// packages/react-router/src/components/Callback.tsx
/**
 * Copyright (c) 2025, WSO2 LLC. (https://www.wso2.com).
 *
 * WSO2 LLC. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

import {FC} from 'react';
import {useNavigate, useLocation} from 'react-router';
import {BaseCallback} from '@asgardeo/react';

/**
 * Props for the Callback component.
 */
export interface CallbackProps {
  /**
   * Callback function called when an error occurs during OAuth processing.
   * @param error - The error that occurred
   */
  onError?: (error: Error) => void;

  /**
   * Optional custom navigation handler.
   * If provided, this will be called instead of the default navigate() behavior.
   * Useful for apps that need custom navigation logic.
   * @param path - The path to navigate to
   */
  onNavigate?: (path: string) => void;
}

/**
 * Handles OAuth callback redirects for React Router applications.
 * Processes authorization code, validates CSRF state, and navigates back to the original path.
 * Automatically handles React Router basename when configured.
 *
 * @example
 * ```tsx
 * <Route path="/callback" element={<Callback />} />
 * ```
 */
const Callback: FC<CallbackProps> = ({
  onError,
  onNavigate,
}) => {
  const navigate = useNavigate();
  const location = useLocation();

  const handleNavigate = (path: string): void => {
    if (onNavigate) {
      onNavigate(path);
      return;
    }

    const fullPath = window.location.pathname;
    const relativePath = location.pathname;
    const basename = fullPath.endsWith(relativePath)
      ? fullPath.slice(0, -relativePath.length).replace(/\/$/, '')
      : '';

    const navigationPath =
      basename && path.startsWith(basename) ? path.slice(basename.length) || '/' : path;

    navigate(navigationPath);
  };

  return (
    <BaseCallback
      onNavigate={handleNavigate}
      onError={
        onError ||
        ((error: Error) => {
          // eslint-disable-next-line no-console
          console.error('OAuth callback error:', error);
        })
      }
    />
  );
};

export default Callback;

// samples/nuxtjs-sdk-playground/pages/callback.vue
<!--
 * Copyright (c) 2025, WSO2 LLC. (https://www.wso2.com).
 *
 * WSO2 LLC. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
-->

<!--
  Callback page for embedded (app-native) authentication flows.

  When Asgardeo redirects back after an embedded authenticator step
  (e.g. social login prompt, MFA), it sends an authorization code to
  the registered callbackUrl.

  <AsgardeoCallback> reads the query-string parameters, posts them to
  POST /api/auth/callback, and redirects the user to afterSignInUrl on
  success — all without a full page reload.

  Register this page as the callbackUrl in nuxt.config.ts:
    asgardeo: {
      callbackUrl: '/callback'   // must match the registered redirect URI
    }
-->
<template>
  <AsgardeoCallback
    @error="onError"
  />
</template>

<script setup lang="ts">
function onError(err: unknown) {
  const message = err instanceof Error ? err.message : String(err ?? 'Callback error');
  console.error('[AsgardeoCallback]', message);
  navigateTo('/');
}
</script>
